from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from app.core.database import get_db
from app.core.security import get_current_user, require_admin
from app.models.setting import Setting

router = APIRouter(prefix="/settings", tags=["settings"])

DEFAULT_SETTINGS = {
    "org_name": ("QuoteForge Inc.", "general"),
    "org_email": ("admin@quoteforge.io", "general"),
    "default_currency": ("USD", "general"),
    "timezone": ("America/New_York", "general"),
    "ai_model": ("gpt-4o-mini", "ai"),
    "ai_temperature": ("0.7", "ai"),
    "ai_max_tokens": ("2000", "ai"),
    "ai_fallback_enabled": ("true", "ai"),
    "smtp_host": ("smtp.gmail.com", "email"),
    "smtp_port": ("587", "email"),
    "smtp_user": ("", "email"),
    "smtp_from": ("noreply@quoteforge.io", "email"),
    "email_footer": ("Generated by QuoteForge", "email"),
    "session_timeout": ("480", "security"),
    "two_factor_enabled": ("false", "security"),
    "password_min_length": ("8", "security"),
    "audit_log_retention": ("90", "security"),
}


@router.get("")
async def get_settings(db: AsyncSession = Depends(get_db), _=Depends(get_current_user)):
    result = await db.execute(select(Setting))
    settings_db = {s.key: s.value for s in result.scalars().all()}

    # Merge defaults with DB values
    merged = {}
    for key, (default_val, category) in DEFAULT_SETTINGS.items():
        merged[key] = settings_db.get(key, default_val)

    return merged


@router.put("")
async def update_settings(data: dict, db: AsyncSession = Depends(get_db), _=Depends(require_admin)):
    for key, value in data.items():
        if key not in DEFAULT_SETTINGS:
            continue
        result = await db.execute(select(Setting).where(Setting.key == key))
        setting = result.scalar_one_or_none()
        if setting:
            setting.value = str(value)
        else:
            _, category = DEFAULT_SETTINGS[key]
            db.add(Setting(key=key, value=str(value), category=category))
    await db.commit()
    return {"message": "Settings updated"}
